Depend on newer PyYAML
Prevents:

```
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]: Traceback (most recent call last):
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/lib/python3/dist-packages/ypconfig/config.py", line 16, in Get
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     document = safe_load(f.read())
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:                ^^^^^^^^^^^^^^^^^^^
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/local/lib/python3.11/dist-packages/yaml/__init__.py", line 94, in safe_load
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     return load(stream, SafeLoader)
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/local/lib/python3.11/dist-packages/yaml/__init__.py", line 72, in load
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     return loader.get_single_data()
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/local/lib/python3.11/dist-packages/yaml/constructor.py", line 37, in get_single_data
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     return self.construct_document(node)
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/local/lib/python3.11/dist-packages/yaml/constructor.py", line 46, in construct_document
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     for dummy in generator:
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/local/lib/python3.11/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     value = self.construct_mapping(node)
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/local/lib/python3.11/dist-packages/yaml/constructor.py", line 204, in construct_mapping
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     return super().construct_mapping(node, deep=deep)
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/local/lib/python3.11/dist-packages/yaml/constructor.py", line 126, in construct_mapping
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     if not isinstance(key, collections.Hashable):
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:                            ^^^^^^^^^^^^^^^^^^^^
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]: AttributeError: module 'collections' has no attribute 'Hashable'
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]: During handling of the above exception, another exception occurred:
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]: Traceback (most recent call last):
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/sbin/ypconfig", line 11, in <module>
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     load_entry_point('ypconfig==1.0.2', 'console_scripts', 'ypconfig')()
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/lib/python3/dist-packages/ypconfig/cli.py", line 53, in main
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     cfgdoc = config.Get(args['--cfg'])
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:              ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:   File "/usr/lib/python3/dist-packages/ypconfig/config.py", line 23, in Get
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]:     raise ValueError("YAML Error in configuration")
Nov 09 12:41:04 pma0.ha.cyberfusion.cloud ypconfig[34706]: ValueError: YAML Error in configuration
```